"""update

Revision ID: 48b20f7a55a8
Revises: 10660f232883
Create Date: 2026-08-18 22:35:13.994028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b20f7a55a8'
down_revision: Union[str, None] = '10660f232883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_celery_hash', table_name='celery_task_executions')
    # ### end Alembic commands ###
